apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
  - host: ecsd00300784.epam.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
